sudo: true
services:
  - docker

before_install:
  - docker pull mongo:3.0.6
  - docker pull elasticsearch:1.7.1
  - docker pull spotify/kafka

language: scala

scala:
  - 2.13.3
  - 2.12.8
  - 2.11.12

jdk:
  - oraclejdk8

script:
  - sbt "scalatest/testOnly com.whisk.docker.MongodbServiceSpec" #spotify executor
  - sbt "scalatest/testOnly com.whisk.docker.ElasticsearchServiceSpec"  #docker-java executor
  - sbt "scalatest/testOnly com.whisk.docker.KafkaServiceSpec" #spotify

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/

before_cache:
  # Tricks to avoid unnecessary cache updates
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt -name "*.lock" -delete
